POST http://localhost:5000/api/blogs
content-type: application/json

{
   "title":"Learning React and Node Js",
   "author":"Shailendra",
   "url":"https://localhost:5000/api/blogs/react",
   "likes": 10
}