POST http://localhost:5000/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbWkxMjMiLCJpZCI6IjYzYWM3YzkxZWIwYTg0NWVhMWZmMTViZCIsImlhdCI6MTY3MjI0ODgyMn0.IHqYuMsxAv0jytSw56qd5uhIJq9CTVFMjrt60gqLP8U

{
   "title":"Learning git pull and merge and Node Js",
   "author":"Samita",
   "url":"https://localhost:5000/api/blogs/react",
   "likes": 12,
   "userId" : "63acb792530fffc11b703e96"
}